name: API Tests

on:
  push:

  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

        with:
          node-version: 20

      - run: npm install

      - run: |
          cd api-tests
          npm install

      - run: |
          cd api-tests
          npx playwright test
